version: '3.4'
name: integration-lutron

services:
  core-simulator:
    image: unfoldedcircle/core-simulator
    restart: "unless-stopped"
    hostname: core-simulator
    environment:
      - UC_INTEGRATION_DISABLE_CERT_VERIFICATION=true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - simulator-data:/data

  intg-lutron:
     build:
       context: ../
       dockerfile: ./dev/Dockerfile
     hostname: lutron
     command: bash -c "UC_INTEGRATION_INTERFACE=$(hostname -i) nodemon -e py,json --exec 'python3 -u' intg-lutron/driver.py"
     volumes:
       - ../:/app

volumes:
  simulator-data:
